refresh_rate: 30 seconds
appenders:
  stdout:
    kind: console
    encoder:
      pattern: "{d(%Y-%m-%d %H:%M:%S)} [{f}:{L}] {h({l})} [{M}] - {m}{n}"
  file:
    kind: rolling_file
    path: "logs/rusty.log"
    encoder:
      pattern: "{d(%Y-%m-%d %H:%M:%S)} [{f}:{L}] {h({l})} [{M}] - {m}{n}"
    policy:
      trigger:
        kind: time
        interval: 1 day
      roller:
        kind: fixed_window
        pattern: "logs/old-rusty-{}.log"
        base: 1
        count: 30
root:
  level: debug
  appenders:
    - stdout
    - file